#! /bin/bash

# necessary to make the notify work in a cronjob run
export DISPLAY=:0

if [[ -d /media/truecrypt8/git ]]; then
	rsync -rltgoDh --stats --log-file=/home/felix/.backup-gits.log /home/felix/git /media/truecrypt8/

	# sudo apt-get install libnotify-bin
	if [[ $? == 0 ]]; then
		notify-send "Git backup" "succesfull"
		exit 0
	else
		notify-send "Git backup" "          failed"
		exit 1
	fi
fi
