#!/bin/bash
if [ "$1" == 'wikipedia_en' ]; then
    shift
    (firefox 'http://en.wikipedia.org/w/index.php?search='"$*"&) > /dev/null 2>&1
elif [ "$1" == 'google' ]; then
    shift
    (firefox 'http://www.google.de/search?q='"$*"&) > /dev/null 2>&1
elif [ "$1" == 'wikipedia_de' ]; then
    shift
    (firefox 'http://de.wikipedia.org/w/index.php?search='"$*"&) > /dev/null 2>&1
fi
