#!/bin/bash

sudo apt-get install python3-pip
pip3 install --upgrade pip
pip3 install --user numpy scipy matplotlib ipython jupyter pandas sympy nose sklearn line-profiler keras tensorflow h5py terminaltables hyperopt
