#!/bin/bash
#-*- coding:utf-8 -*-

DIR="$( cd "$( dirname "$0" )" && pwd )"

rsync -aPhr --exclude-from=$DIR/exclude-cpba /home/felix/Dropbox/Bachelorarbeit /home/felix/git/misc/
rsync -aPh /home/felix/.jshintrc /home/felix/git/misc/Bachelorarbeit/Style\ Guides

# copy all files to the special geoformchart dir except gfc_config.py
rsync -aPh /home/felix/git/geo/cn/js/geoformchart.js /home/felix/git/geo/geoformchart/js/
rsync -aPh /home/felix/git/geo/cn/css/geoformchart.css /home/felix/git/geo/geoformchart/css/
rsync -aPh /home/felix/git/geo/cn/WEB-INF/cgi/get-database-structure.cgi /home/felix/git/geo/geoformchart/cgi/
rsync -aPh /home/felix/git/geo/cn/WEB-INF/cgi/get-chart-data.cgi /home/felix/git/geo/geoformchart/cgi/
rsync -aPh /home/felix/git/geo/cn/WEB-INF/cgi/geoformchart.py /home/felix/git/geo/geoformchart/cgi/

# copy to the git dir
rsync -aPhr /home/felix/git/geo/geoformchart/ /home/felix/git/misc/Bachelorarbeit/Code
