#! /bin/bash

if [ ! `id -u` -eq 0 ]; then
    echo "Please be so kind to run me as root. Thank you."
    exit 1
fi

echo "Resetting to gay Beuth DNS Server"

$PWD/make_dns_servers_beuth
$PWD/uni_conn.py

