#! /bin/bash

if [[ ! -d /home/felix/git/a4 ]]; then
	echo "This does not look like Felix's computer. Please edit the paths to fit your home dir, HRZ account and git location."
	exit 1
fi

TMP_DIR=/home/felix/tmp.uni.8PEy9Blrty
A4_DIR=/home/felix/git/a4
HRZ_NAME=s38371
HRZ_PASSWORD=wlanpw23

wget --restrict-file-names=ascii -r -I "~knabe/fach/scala/mb-ats5/uebung/ueb??" -R "*.html*" -np -nH -N -P $TMP_DIR 'http://public.beuth-hochschule.de/~knabe/fach/scala/mb-ats5/uebung/'
wget --restrict-file-names=ascii -r -A "*.pdf" -np -nH -N -P $TMP_DIR 'http://public.beuth-hochschule.de/~knabe/fach/scala/mb-ats5/unterricht/'
wget --restrict-file-names=ascii -r -A "*.pdf" --no-check-certificate --user=$HRZ_NAME --password=$HRZ_PASSWORD -np -nH -l 1 -N -P $TMP_DIR 'https://public.beuth-hochschule.de/~steppat/2011_WS/QM/'

# parse url encoding of special chars in file names
url_encoding_files=$(mktemp)
find $TMP_DIR -type f -name "*%*" > $url_encoding_files

while read file; do
	mv -v "$file" "$(echo $file | sed 's/%C3%9C/Ue/g;s/%C3%84/Ae/g;s/%C3%96/Oe/g;s/%C3%A4/ae/g;s/%C3%B6/oe/g;s/%C3%BC/ue/g;s/%C3%9F/ss/g;s/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g')"
done < $url_encoding_files

rm $url_encoding_files

# copy to git
rsync -r $TMP_DIR/~knabe/fach/scala/mb-ats5/uebung/ueb?? $TMP_DIR/~knabe/fach/scala/mb-ats5/unterricht/ $A4_DIR/scala
rsync -r $TMP_DIR/~steppat/2011_WS/QM/ $A4_DIR/qm/material

 cd $A4_DIR

 # commit if something changed
 if [[ -n $(git status --porcelain) ]]; then
	 git pull
	 git add scala/
	 git add qm/material/
	 git commit -m "Automated commit with potentially new stuff of QM and Scala"
	 git push
 else
	 echo -n -e "\nNothing changed, nothing to commit.\n"
 fi
 echo "Done."
