#! /bin/sh

chattr -i /etc/resolv.conf;
rm /etc/resolv.conf;
cat <<EOF> /etc/resolv.conf
options attempts:1 timeout:1 rotate 

nameserver 85.214.73.63
nameserver 194.150.168.168 
nameserver 213.73.91.35
nameserver 80.237.196.2
nameserver 194.95.202.198
EOF
chattr +i /etc/resolv.conf;
