#! /bin/bash

if [[ ! $(id -u) -eq 0 ]]; then
    echo "Must be run as root." >&2
	 exit 1
fi

MY_SOURCES="deb http://felix-stiehler.de/apt binary/"
SOURCES_TMP_PREFIX="/tmp/.sources_choice_"

# Test if we have squeeze sources already
grep -i "squeeze" /etc/apt/sources.list > /dev/null
if [[ ! $? == 0 ]]; then
	printf "\n"
	cat /etc/apt/sources.list
	read -p $'\n'"It seems like you do not have squeeze sources configured. Above are the current sources. Continue with source configuration? [y/n] " ok
	if [[ $ok == n || $ok == N ]]; then
		echo "Aborting source config."
		exit 0
	fi
fi

# Saving the choices as files
cat <<-'EOF'> "$SOURCES_TMP_PREFIX"1
	# official sources
	deb http://ftp.debian.org/debian squeeze main contrib non-free
	deb http://security.debian.org/ squeeze/updates main contrib non-free
	deb http://ftp.debian.org/debian squeeze-updates main

	# my own sources
	deb http://felix-stiehler.de/apt binary/
EOF

cat <<-'EOF'> "$SOURCES_TMP_PREFIX"2
	# official sources
	deb http://ftp.SUBDOMAIN.debian.org/debian squeeze main contrib non-free
	deb http://security.debian.org/ squeeze/updates main contrib non-free
	deb http://ftp.SUBDOMAIN.debian.org/debian squeeze-updates main

	# my own sources
	deb http://felix-stiehler.de/apt binary/
EOF

cat <<-'EOF'> "$SOURCES_TMP_PREFIX"3
	# official sources
	deb http://cdn.debian.net/debian squeeze main contrib non-free
	deb http://security.debian.org/ squeeze/updates main contrib non-free
	deb http://cdn.debian.net/debian squeeze-updates main

	# my own sources
	deb http://felix-stiehler.de/apt binary/
EOF

# Managing the sources
printf "\n(1) Use the standart source ftp.debian.org\n"
printf "(2) Use country specific source (e.g. ftp.de.debian.org)\n"
printf "(3) Use the CDN cdn.debian.net\n"
printf "(a) Abort\n"
read -p "Your choice: " choice

if [[ $choice == a || $choice == A ]]; then
	echo "Aborting source config."
	exit 0
fi

if [[ ! $choice =~ ^[1-3]$ ]]; then
	echo "No valid choice entered. Using the default source ftp.debian.org."
	choice=1
else
	if [[ $choice == 2 ]]; then
		read -p "Please enter the subdomain (e.g. \"de\"): " subdomain
		sed -i "s/SUBDOMAIN/$subdomain/g" "$SOURCES_TMP_PREFIX"2
	fi
fi

echo "You can find your old sources in \"sources.list.old\""
cp /etc/apt/sources.list /etc/apt/sources.list.old
cp "$SOURCES_TMP_PREFIX"$choice /etc/apt/sources.list

printf "\n"
cat /etc/apt/sources.list
read -p $'\n'"This is the new sources.list. Press enter to continue. " ok

exit 0
